spring:
  application:
    name: ApiGateway

  cloud:
    gateway:
      routes:
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
        - id: order_service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
        - id: auth_service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**
